[project]
name = "scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.1",
    "numpy>=2.2.6",
    "regex>=2025.11.3",
    "tiktoken>=0.12.0",
    "torch>=2.9.1",
]
